#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# vim:sta:si:sw=4:sts=4:et:
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2012             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# The Check_MK official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Check has been developed using a Emerson Network Power
# Manufacturer			Liebert Corporation
# Device Model			Liebert NX
# Device Firmware Version	I190R200M270
# Agent Type			IntelliSlot Web Card
# Agent App Firmware Version	3.310.2
# Agent App Firmware Label	IS-WEBLB_HID7_3.310.2_048951
# Agent Boot Firmware Version	3.310.2
# Agent Boot Firmware Label	IS-WEBLB_HID7_3.310.2_048951
# Agent Hardware ID		7
#
# +------------------------------------------------------------------+
# | This file has been contributed by:                               |
# |                                                                  |
# | Václav Ovsík <vaclav.ovsik@gmail.com>             Copyright 2014 |
# +------------------------------------------------------------------+

# Example info:
#  [[['1']], [['761', '.1.3.6.1.4.1.476.1.42.3.2.1.74', '4115079590']]]


def inventory_lgp_env_cond(info):
    if len(info) == 0:
        return
    (((num,),), table) = info
    if num is not None:
        return [ (None, None) ]
    return

def check_lgp_env_cond(item, params, info):
    (((num,),), table) = info
    if int(num) == 0:
        return (0, 'OK')
    cond = []
    for id, oid, time in table:
         cond.append("(id: {}, oid: {}, time: {})".format(id, oid, time))
    return (2, "CRIT - {} condition(s) present: TODO... ".format(num)
            + ", ".join(cond))


check_info['lgp_env_cond'] = (check_lgp_env_cond,
            'Liebert Conditions', 0, inventory_lgp_env_cond)

snmp_info['lgp_env_cond'] = [
    ('.1.3.6.1.4.1.476.1.42.3.2', [
        '2', # LIEBERT-GP-CONDITIONS-MIB::lgpConditionsPresent
    ]),
    ('.1.3.6.1.4.1.476.1.42.3.2.3.1', [
        '1', # LIEBERT-GP-CONDITIONS-MIB::lgpConditionId
        '2', # LIEBERT-GP-CONDITIONS-MIB::lgpConditionDescr
        '3', # LIEBERT-GP-CONDITIONS-MIB::lgpConditionTime
    ]),
]

snmp_scan_functions['lgp_env_cond'] = lambda oid: \
        oid('.1.3.6.1.2.1.1.2.0').startswith('.1.3.6.1.4.1.476.1.42')
